=== doubend/test/csyy/src/main/resources/system/conf/query/sql.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2011 (http://www.altova.com)-->
<xs:schema targetNamespace="x-schema:sql.xsd"
 xmlns="x-schema:sql.xsd"
 xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="where">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="if" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
		<xs:element name="insert">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="sql"/>
				<xs:element ref="values"/>
				<xs:choice>
					<xs:element ref="trim"/>
					<xs:element ref="where"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="key" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value=""/>
						<xs:enumeration value="9999"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="des" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value=""/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="author" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value=""/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="update">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="sql"/>
				<xs:element ref="set"/>
				<xs:choice>
					<xs:element ref="trim"/>
					<xs:element ref="where"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="key" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value=""/>
						<xs:enumeration value="9999"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="des" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value=""/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="author" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="jyhu"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="trim">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="if" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="prefix" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="where"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="sqlXml">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="select"/>
				<xs:element ref="update" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="sql">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="select * from t_user"/>
				<xs:enumeration value="update user "/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="set">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="if"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="select">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="sql"/>
				<xs:element ref="trim"/>
				<xs:element ref="order"/>
				<xs:element ref="group"/>
			</xs:sequence>
			<xs:attribute name="resultType" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value=""/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="parameterType" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value=""/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="key" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value=""/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="des" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value=""/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="author" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="jyhu"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="order">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="exp"/>
			</xs:sequence>
			<xs:attribute name="value" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="desc"/>
						<xs:enumeration value="asc"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="group">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="exp"  minOccurs="1"/>
				<xs:element ref="having"  minOccurs="1"/>
			</xs:sequence>
			
			
		</xs:complexType>
	</xs:element>
	<xs:element name="if">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="exp"/>
			</xs:sequence>
			<xs:attribute name="test" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="#name!=22"/>
						<xs:enumeration value="#name!=null"/>
						<xs:enumeration value="name!=null"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="prefix">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="and"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="exp">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value=" name"/>
				<xs:enumeration value="name=#{name}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="having">
		<xs:simpleType>
			<xs:restriction base="xs:string">
			
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== doubend/test/csyy/src/main/resources/system/conf/query/employmentInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<sqlXml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="sql.xsd">
<select key="queryEmploymentByYear" des="查询各区域就业人数">
 	<sql> 
  		select t1.QY,t.RS from rktjxx_rkstj t left join rkxx_bm_area t1 on t.QY = t1.code
  		 where t.ZTFL="0700"  and t.RKJBLX="0" and t.XB="0" and t.HYZK="00" and t.NLD="00"  and t.TJNF=#{nian}
    </sql>
</select>
<select key="queryThreeIndustryByYear" des="查询各区域的三大产业就业人数及总的就业人数">
 	<sql> 
  		select t1.QY,t.ZTFL,t.XB,t.RS from rktjxx_rkstj t left join rkxx_bm_area t1 on t.QY = t1.code
  		 where t.ZTFL in ("0701","0702","0703","0700") and t.RKJBLX="0" and t.XB in("0","1","2")
		and t.HYZK="00" and t.NLD="00" and t.TJNF=#{nian}
    </sql>
</select>
<select key="queryOnceEmployment" des="根据年份去查询再就业不同类型的人数">
	<sql>
		select  t1.QY,t.ZTFL,t.RS from rktjxx_rkstj t left join rkxx_bm_area t1 on t.QY = t1.code 
		where t.HYZK="00" and t.NLD="00" and t.XB="0" and t.RKJBLX="0" and t.ZTFL in("0704","0705","0706") and t.TJNF=#{nian} order by t.QY
	</sql>
</select>
<select key="queryEdudegree" des="根据年份查询全县一产,二产,三产 不同文化程度的人数以及参保的人数">
	<sql>
		SELECT
			t.ZTFL,
			CASE
		WHEN t.WHCD = "00" THEN
			"all"
		WHEN t.WHCD = "10" THEN
			"onUniversity"
		WHEN t.WHCD = "30" THEN
			"juniorCollege"
		WHEN t.WHCD IN ("40", "60") THEN
			"middleStudent"
		WHEN t.WHCD in ("91","93") THEN
			"underGradeStudent"
		END AS "edu",
		 sum(t.RS) "total"
		FROM
			rktjxx_rkstj t
		LEFT JOIN rkxx_bm_tjztfl t2 ON t.ZTFL = t2. CODE
		WHERE
			t.XB = "0"
		AND t.HYZK = "00"
		AND t.RKJBLX = "0"
		AND t.NLD = "00"
		AND t.ZTFL IN ("0701", "0702", "0703","0810","0811","0812")
		AND t.TJNF = #{nian}
		AND t.QY = "000"
		GROUP BY
			t.ZTFL,
			edu;
	</sql>
</select>

</sqlXml>

=== doubend/test/csyy/src/main/resources/system/conf/query/security.xml
<?xml version="1.0" encoding="UTF-8"?>
<sqlXml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="sql.xsd">
  <select key="queryMap" des="社保地图显示" author="dxliug">
   <sql>
    select t1.* ,t2.QY as hqy from rktjxx_rkstj t1
    left JOIN rkxx_bm_area t2 on t1.QY = t2.CODE
    LEFT JOIN rkxx_bm_tjztfl t3 
     on t1.ZTFL = t3.CODE   
     where t1.tjnf = #{nian} and t1.ZTFL in (0800,0801,0802,0803,0804,0805,0806)
     order by qy asc
   </sql>
  </select>
  <select key="queryNum" des="查询总人口" author="dxliug">
   <sql>
    select t2.QY,SUM(rs) as ars from rktjxx_rkstj t1 left JOIN rkxx_bm_area t2 on t1.QY = t2.CODE
     where xb = 0 
      and ZTFL = 0000 and MZ = 00 and NLD = 00 and whcd  = 00 
      #<!-- and RKJBLX = 0 -->
      AND tjnf =  #{nian}
    GROUP BY qy 
    order by qy asc 
   </sql>
  </select>
  
  <select key="querySocial" des="社保情况饼图" author="dxliug">
    <sql>
     select t1.* ,t2.QY as hqy from rktjxx_rkstj t1
    left JOIN rkxx_bm_area t2 on t1.QY = t2.CODE
    LEFT JOIN rkxx_bm_tjztfl t3 
     on t1.ZTFL = t3.CODE 
    </sql>
    <trim prefix="where">
     <if test="#nian!=null" prefix="and">
       <exp>
            t1.TJNF = #{nian}
         </exp>
     </if>
     <if test="#qy!=null" prefix="and" >
          <exp>
            t2.QY = #{qy}
          </exp>
      </if>
    </trim>
    and t1.ZTFL in (0801,0802,0803,0804,0805,0806)
    order by qy asc
  </select>
  
  <select key="queryAmount" des="参保金额结构图" author="dxliug">
   <sql>
	select t1.*,t2.SBJN as hsbjn,t3.QY as hqy from rktjxx_sbxx t1
	LEFT JOIN rkxx_bm_sbjnlx t2 ON t1.SBJJLX = t2.CODE
	left JOIN rkxx_bm_area t3 on t1.QY = t3.CODE
    where t1.tjnf = #{nian} and t1.SBJJLX in (03,04,05)
    order by qy asc
  </sql>
  </select>
  <select key="queryPeople" des="参保人数查询" author="dxliug">
  <sql>
   select t1.RS,t1.ZTFL,t1.QY,t2.TJZTFL as TJZTFL,t3.QY as hqy from rktjxx_rkstj t1
	LEFT JOIN rkxx_bm_tjztfl t2 ON t1.ZTFL = t2.CODE
	left JOIN rkxx_bm_area t3 on t1.QY = t3.CODE
    where t1.tjnf = #{nian} and t1.ZTFL in (0807,0808,0809)
        order by qy asc
    </sql>
  </select>
 <!--  <select key="" des="贫困家庭情况" author="dxliug">
    <sql>
     select t1.RS ,t1.ZTFL,t2.TJZTFL,t1.TJNF,t3.QY from rktjxx_rkstj t1
     LEFT JOIN rkxx_bm_tjztfl t2 on  t1.ZTFL = t2.CODE 
     LEFT JOIN rkxx_bm_area t3 on t1.QY = t3.CODE
     where  t1.ZTFL in (0902,0903,0908,0906,0907)     
            t1.tjnf = #{nian}
   </sql>
  </select>
  
  <select key="" des="查询支出金额" author="dxliug">
   <sql>
     select t1.JFZCLX,t2.TPNL,t1.SJZC,t1.TJNF,t3.QY from rktjxx_rkfyzc t1 LEFT JOIN rkxx_bm_rkjfzclx t2 ON t1.JFZCLX = t2.CODE
     LEFT JOIN rkxx_bm_area t3 ON t1.QY = t3.CODE
     where t1.JFZCLX in (0001,0002)
           t1.tjnf = #{nian}
   </sql>
  </select> -->
  
  
  </sqlXml>

=== doubend/test/csyy/src/main/resources/system/conf/query/educationInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<sqlXml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="sql.xsd">
<select key="getTeaOffice"  des="教育机构数量" author="dxliug">
   <sql> 
    select sum(r.JGSL) JGSL,sum(r.JZRYS) JZRYS ,r.ZXSRS,r.XXLX,k.QY,b.EDU from RKTJXX_JYXX r 
           left join rkxx_bm_area k on r.QY=k.code 
           left join rkxx_bm_eduschool b on r.XXLX = b.CODE
           where  r.TJNF = #{nian}
         GROUP BY r.qy,b.edu 
       ORDER BY r.QY asc
   </sql>
</select>
<select key="queryTeacherCount" des="查询教师数量" author="dxliug">
 <sql> 
  	select r.* ,k.QY as hQY,b.EDU,SUM(JZRYS) as njzrys from RKTJXX_JYXX r 
           left join rkxx_bm_area k on r.QY=k.code 
           left join rkxx_bm_eduschool b on r.XXLX = b.CODE
           where r.tjnf = #{nian} and b.EDU != '幼儿园' 
           GROUP BY hqy,edu ORDER BY qy ASC
   </sql>
</select>
<select key="queryTSCount" des="查询师生对比数量" author="dxliug">
 <sql> 
  	select sum(r.ZXSRS) as SZXSRS,SUM(r.JZRYS) as SJZRYS, r.* ,k.QY as hQY from RKTJXX_JYXX r 
           left join rkxx_bm_area k on r.QY=k.code
           where  r.TJNF = #{nian}
            GROUP BY r.QY ORDER BY r.QY ASC
   </sql>
</select>
 <select key="queryReceiveEd" des="受教育情况" author="dxliug">
  <sql>
    select j.*,f.EDU,k.QY as hqy  from rktjxx_rkstj j left join frxx_bm_edudgree f on j.WHCD = f.CODE
    left join rkxx_bm_area k on j.QY = k.CODE
    where j.tjnf = #{nian}
          and j.WHCD not in(00,92,91)
    GROUP BY QY,EDU order by qy asc
  </sql>
 
 </select>
 <select key="queryTeaAndStu" des="查询老师和学生 分小学 初中 高中" author="frj">
 <sql>
 	SELECT
a.QY ,r.XXLX ,r.ZXSRS,r.JZRYS,r.TJNF
FROM
	rktjxx_jyxx r
LEFT JOIN rkxx_bm_area a ON a. CODE = r.QY
WHERE
	r.XXLX IN ("02", "03", "04")
AND r.TJNF BETWEEN #{befNian} AND #{nian}
ORDER BY r.QY ASC,r.XXLX ASC ,r.TJNF DESC
 </sql>
 </select>
 
 <select key="queryEducation" des="受教育与未受教育情况" author="dxliug">
  <sql>
    select r.*,b.QY as hqy,SUM(r.rs) as nrs  from rktjxx_rkstj r LEFT JOIN rkxx_bm_area b on r.QY = b.CODE
    where r.whcd = 92 and r.TJNF = #{nian}
    GROUP BY r.QY
    UNION ALL
    select t.*,c.QY as hqy ,SUM(t.rs) as nrs from rktjxx_rkstj t LEFT JOIN rkxx_bm_area c on t.QY = c.CODE
    where t.WHCD != 92 and t.TJNF = #{nian}
    GROUP BY t.QY
    order by qy asc
   </sql>
 </select>
 
 <select key="queryWeiEducation" des="未受教育的数据" author="dxliug">
    <sql>
    select j.*,f.EDU,k.QY as hqy  from rktjxx_rkstj j left join frxx_bm_edudgree f on j.WHCD = f.CODE
    left join rkxx_bm_area k on j.QY = k.CODE
    where j.tjnf = #{nian}
          and j.WHCD != 00
    GROUP BY QY,EDU order by qy asc
    </sql>
 </select>
</sqlXml>
